#!/bin/bash

CONTAINER_ID=$(
    docker run \
	-d \
	-p 127.0.0.1:3000:3000 \
	-p 127.0.0.1:8000:8000 \
	-p 127.0.0.1:25482:25482 \
	-p 127.0.0.1:5432:5432 \
	-p 127.0.0.1:80:80 \
	andreyutkin/taskdb-provisioned:latest
)

docker exec -it $CONTAINER_ID /bin/bash -i

docker kill $CONTAINER_ID
